project_id = "rbvnrmrwzhakkddlfmvs"

[functions.travel-chat]
verify_jwt = false

[functions.embed]
verify_jwt = false

[functions.ai-companion]
verify_jwt = false

[functions.generate-schedule]
verify_jwt = false
