import { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { Share2, Download, Compass, MapPin, Wifi, DollarSign, Users, Briefcase } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from '@/hooks/use-toast';
import html2canvas from 'html2canvas';

interface TripSummaryCardProps {
  destination: string;
  totalDays: number;
  totalActivities: number;
  budgetSummary: string;
  categories: Record<string, number>;
}

function getWorkCompatibility(categories: Record<string, number>, total: number): number {
  const workCount = categories['work'] || 0;
  const foodCount = categories['food'] || 0;
  // Work compat = weighted mix of work activities + food (need fuel) + base
  return Math.min(95, Math.round(((workCount * 3 + foodCount) / Math.max(total, 1)) * 100 + 40));
}

function getCommunityStrength(total: number): string {
  if (total >= 35) return 'Strong';
  if (total >= 20) return 'Growing';
  return 'Emerging';
}

function getMonthlyEstimate(budgetSummary: string): string {
  // Try to extract numbers from budget summary
  const nums = budgetSummary.match(/[\d,]+/g);
  if (nums && nums.length > 0) {
    const daily = parseInt(nums[0].replace(',', ''));
    if (daily > 0 && daily < 500) return `$${(daily * 30).toLocaleString()}`;
    if (daily >= 500) return `$${daily.toLocaleString()}`;
  }
  return '$1,800';
}

export default function ShareableTripCard({ destination, totalDays, totalActivities, budgetSummary, categories }: TripSummaryCardProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [sharing, setSharing] = useState(false);

  const city = destination.split('—')[0]?.trim() || destination;
  const workCompat = getWorkCompatibility(categories, totalActivities);
  const community = getCommunityStrength(totalActivities);
  const monthlyCost = getMonthlyEstimate(budgetSummary);

  const captureCard = async (): Promise<Blob | null> => {
    if (!cardRef.current) return null;
    const canvas = await html2canvas(cardRef.current, {
      backgroundColor: null,
      scale: 2,
      useCORS: true,
      logging: false,
    });
    return new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
  };

  const handleShare = async () => {
    setSharing(true);
    try {
      const blob = await captureCard();
      if (!blob) throw new Error('Failed to capture');

      if (navigator.share && navigator.canShare?.({ files: [new File([blob], 'nomaaad-trip.png', { type: 'image/png' })] })) {
        await navigator.share({
          title: `My Nomad Life in ${city}`,
          text: `Check out my travel plan for ${city} — generated by Nomaaad ✈️`,
          files: [new File([blob], 'nomaaad-trip.png', { type: 'image/png' })],
        });
      } else {
        // Fallback: download
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `nomaaad-${city.toLowerCase().replace(/\s+/g, '-')}.png`;
        a.click();
        URL.revokeObjectURL(url);
        toast({ title: '📸 Card downloaded!', description: 'Share it on your favorite social media.' });
      }
    } catch (e) {
      if ((e as Error).name !== 'AbortError') {
        toast({ title: 'Error', description: 'Could not share. Try downloading instead.', variant: 'destructive' });
      }
    } finally {
      setSharing(false);
    }
  };

  const handleDownload = async () => {
    setSharing(true);
    try {
      const blob = await captureCard();
      if (!blob) throw new Error('Failed');
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `nomaaad-${city.toLowerCase().replace(/\s+/g, '-')}.png`;
      a.click();
      URL.revokeObjectURL(url);
      toast({ title: '📸 Downloaded!' });
    } catch {
      toast({ title: 'Error', variant: 'destructive' });
    } finally {
      setSharing(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.2 }}
      className="mt-10"
    >
      <h3 className="font-semibold text-foreground text-sm mb-3 flex items-center gap-2">
        <Share2 className="h-4 w-4 text-primary" />
        Share your trip
      </h3>

      {/* The actual card to capture */}
      <div
        ref={cardRef}
        className="relative w-full max-w-sm mx-auto rounded-[1.75rem] overflow-hidden"
        style={{ aspectRatio: '9/16' }}
      >
        {/* Background gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-[hsl(var(--primary))] via-[hsl(var(--primary)/0.8)] to-[hsl(var(--chart-2))]" />
        
        {/* Decorative circles */}
        <div className="absolute top-[-20%] right-[-15%] w-[60%] h-[60%] rounded-full bg-[hsl(var(--background)/0.08)]" />
        <div className="absolute bottom-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-[hsl(var(--background)/0.06)]" />

        {/* Content */}
        <div className="relative z-10 flex flex-col h-full p-7 text-[hsl(var(--primary-foreground))]">
          {/* Top — Logo */}
          <div className="flex items-center gap-2 mb-auto">
            <div className="w-8 h-8 rounded-xl bg-[hsl(var(--background)/0.2)] flex items-center justify-center">
              <Compass className="h-4 w-4" />
            </div>
            <span className="font-bold text-sm tracking-tight opacity-90">nomaaad</span>
          </div>

          {/* Center — Main info */}
          <div className="my-auto space-y-6">
            <div>
              <p className="text-xs uppercase tracking-[0.2em] opacity-70 mb-2">My Nomad Life in</p>
              <h2 className="text-3xl font-bold leading-tight">{city}</h2>
              <p className="text-sm opacity-70 mt-1">{totalDays} days · {totalActivities} activities</p>
            </div>

            {/* Stats */}
            <div className="space-y-3">
              {[
                { icon: DollarSign, label: 'Monthly cost', value: monthlyCost },
                { icon: Briefcase, label: 'Work compatibility', value: `${workCompat}%` },
                { icon: Users, label: 'Community', value: community },
              ].map((stat, i) => (
                <div key={i} className="flex items-center gap-3 bg-[hsl(var(--background)/0.12)] rounded-2xl px-4 py-3">
                  <stat.icon className="h-4 w-4 opacity-80" />
                  <span className="text-xs opacity-70 flex-1">{stat.label}</span>
                  <span className="text-sm font-bold">{stat.value}</span>
                </div>
              ))}
            </div>

            {/* Category breakdown */}
            <div className="flex gap-2 flex-wrap">
              {Object.entries(categories)
                .sort(([, a], [, b]) => b - a)
                .slice(0, 4)
                .map(([cat, count]) => (
                  <span
                    key={cat}
                    className="px-3 py-1 rounded-full bg-[hsl(var(--background)/0.15)] text-xs font-medium capitalize"
                  >
                    {cat} × {count}
                  </span>
                ))}
            </div>
          </div>

          {/* Bottom — Branding */}
          <div className="mt-auto pt-4 border-t border-[hsl(var(--background)/0.15)]">
            <p className="text-[10px] opacity-50 text-center">Generated by Nomaaad · nomaaad.lovable.app</p>
          </div>
        </div>
      </div>

      {/* Share / Download buttons */}
      <div className="flex gap-3 mt-4 max-w-sm mx-auto">
        <Button
          onClick={handleShare}
          disabled={sharing}
          className="flex-1 rounded-xl h-11 gap-2"
        >
          <Share2 className="h-4 w-4" />
          Share
        </Button>
        <Button
          onClick={handleDownload}
          disabled={sharing}
          variant="outline"
          className="rounded-xl h-11 gap-2"
        >
          <Download className="h-4 w-4" />
          Save
        </Button>
      </div>
    </motion.div>
  );
}
